# Generated by Django 2.0.5 on 2018-05-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sede', models.CharField(max_length=45)),
                ('Descrizione', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CF', models.CharField(max_length=30)),
                ('Cognome', models.CharField(max_length=45)),
                ('Nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MotPrestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motivazione', models.CharField(max_length=45)),
                ('Descrizione', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.PositiveIntegerField(null=True)),
                ('DataProvvedimento', models.DateField(null=True)),
                ('Ammontare', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('NumeroMandato', models.PositiveIntegerField(null=True)),
                ('DataMandatoPagamento', models.DateField(null=True)),
                ('MeseAnnoCedolino', models.DateField(null=True)),
                ('InEssere', models.NullBooleanField()),
                ('DataCessazione', models.DateField(null=True)),
                ('CCIA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.CCIA')),
                ('CF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.Dipendente')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Restituzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=45)),
                ('Descrizione', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TassoInteresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=45)),
                ('Percentuale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Inizio', models.DateField(null=True)),
                ('Fine', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMoneta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20)),
                ('Simbolo', models.CharField(max_length=1)),
                ('Descrizione', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProvvedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=45)),
                ('Descrizione', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descrizione', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='prestito',
            name='ModRestituzione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.Restituzione'),
        ),
        migrations.AddField(
            model_name='prestito',
            name='Motivazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.MotPrestito'),
        ),
        migrations.AddField(
            model_name='prestito',
            name='Tasso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.TassoInteresse'),
        ),
        migrations.AddField(
            model_name='prestito',
            name='TipoProvvedimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.TipoProvvedimento'),
        ),
        migrations.AddField(
            model_name='prestito',
            name='Valuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CDC.TipoMoneta'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDC.Question'),
        ),
    ]
