# Generated by Django 2.0.5 on 2018-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDC', '0002_auto_20180601_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Valuta',
        ),
        migrations.AlterField(
            model_name='ccia',
            name='Sede',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
