# Generated by Django 2.0.5 on 2018-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDC', '0003_auto_20180602_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='Ammontare',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
